//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rep
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cliente
    {
        public Cliente()
        {
            this.Pedido = new HashSet<Pedido>();
            this.Cliente_Contato = new HashSet<Cliente_Contato>();
            this.Cliente_Endereco = new HashSet<Cliente_Endereco>();
        }
    
        public int id_Cliente { get; set; }
        public string nome { get; set; }
        public string cpf { get; set; }
        public Nullable<System.DateTime> dataNascimento { get; set; }
        public string login { get; set; }
        public string Senha { get; set; }
    
        public virtual ICollection<Pedido> Pedido { get; set; }
        public virtual ICollection<Cliente_Contato> Cliente_Contato { get; set; }
        public virtual ICollection<Cliente_Endereco> Cliente_Endereco { get; set; }
    }
}
