//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rep
{
    using System;
    using System.Collections.Generic;
    
    public partial class Produto
    {
        public Produto()
        {
            this.Pedido = new HashSet<Pedido>();
        }
    
        public int id { get; set; }
        public string nome { get; set; }
        public string marca { get; set; }
        public Nullable<decimal> preco { get; set; }
        public string tipo { get; set; }
        public string lote { get; set; }
        public string descricao { get; set; }
        public Nullable<System.DateTime> validade { get; set; }
    
        public virtual ICollection<Pedido> Pedido { get; set; }
    }
}
