//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rep
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class bd_SysFarmaEntities : DbContext
    {
        public bd_SysFarmaEntities()
            : base("name=bd_SysFarmaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Tabela_Pedido> Tabela_Pedido { get; set; }
        public DbSet<Cliente> Cliente { get; set; }
        public DbSet<Cliente_Contato> Cliente_Contato { get; set; }
        public DbSet<Cliente_Endereco> Cliente_Endereco { get; set; }
        public DbSet<Produto> Produto { get; set; }

        public System.Data.EntityState added { get; set; }

        internal System.Data.EntityState Modified()
        {
            throw new NotImplementedException();
        }

        public System.Data.EntityState Delete { get; set; }
    }
}
