//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repositorio
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class bd_SysFarmaEntities : DbContext
    {
        public bd_SysFarmaEntities()
            : base("name=bd_SysFarmaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
        public DbSet<Tabela_Pedido> Tabela_Pedido { get; set; }
        public DbSet<tbl_Cliente> tbl_Cliente { get; set; }
        public DbSet<tbl_Cliente_Contato> tbl_Cliente_Contato { get; set; }
        public DbSet<tbl_Cliente_Endereco> tbl_Cliente_Endereco { get; set; }
        public DbSet<tbl_Produto> tbl_Produto { get; set; }
    }
}
