//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repositorio
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tabela_Pedido
    {
        public Tabela_Pedido()
        {
            this.tbl_Produto = new HashSet<tbl_Produto>();
        }
    
        public int numero { get; set; }
        public Nullable<decimal> valor { get; set; }
        public int id_Cliente { get; set; }
        public System.DateTime data { get; set; }
    
        public virtual tbl_Cliente tbl_Cliente { get; set; }
        public virtual ICollection<tbl_Produto> tbl_Produto { get; set; }
    }
}
