//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repositorio
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Cliente
    {
        public tbl_Cliente()
        {
            this.Tabela_Pedido = new HashSet<Tabela_Pedido>();
            this.tbl_Cliente_Contato = new HashSet<tbl_Cliente_Contato>();
            this.tbl_Cliente_Endereco = new HashSet<tbl_Cliente_Endereco>();
        }
    
        public int id_Cliente { get; set; }
        public string nome { get; set; }
        public string cpf { get; set; }
        public Nullable<System.DateTime> dataNascimento { get; set; }
    
        public virtual ICollection<Tabela_Pedido> Tabela_Pedido { get; set; }
        public virtual ICollection<tbl_Cliente_Contato> tbl_Cliente_Contato { get; set; }
        public virtual ICollection<tbl_Cliente_Endereco> tbl_Cliente_Endereco { get; set; }
    }
}
