//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repositorio
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Cliente_Contato
    {
        public int id { get; set; }
        public int id_Cliente { get; set; }
        public string telefone { get; set; }
        public string email { get; set; }
    
        public virtual tbl_Cliente tbl_Cliente { get; set; }
    }
}
